create sequence hibernate_sequence start 1 increment 1;

create table reader
(
    id         int generated by default as identity primary key,
    full_name  varchar(100) not null unique,
    birth_date varchar      not null,
    password   varchar      not null,
    username   varchar(20)  not null,
    role       varchar(100) not null
);

create table author
(
    id         int generated by default as identity primary key,
    first_name varchar not null,
    last_name  varchar not null
);

create table book
(
    id             int generated by default as identity primary key,
    author_id      int references author (id),
    title          varchar   not null,
    issue_datetime timestamp not null,
    isbn           varchar   not null
);

create table book_amount
(
    book_id    int primary key references book (id),
    amount     int not null,
    min_amount int
);

create table reader_book
(
    id           int generated by default as identity primary key,
    instance     int           not null,
    reader_id    int references reader (id),
    book_id      int references book (id),
    taken_at     timestamp     not null,
    reading_days int default 1 not null
);

create table publisher_book
(
    id                int primary key generated by default as identity,
    created_at        timestamp NOT NULL,
    status            varchar   not null,
    author_first_name varchar   not null,
    author_last_name  varchar   not null,
    title             varchar   not null,
    isbn              varchar   not null,
    issue_date_time   timestamp not null
)