spring:



  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: 'kz.bisen.springwebapp1.project2Boot.kafka.BookIsbnMessage'
            type:
              mapping: 'kz.bisen.springcourse.springpublishingwebapp.kafka.BookIsbnMessage:kz.bisen.springwebapp1.project2Boot.kafka.BookIsbnMessage'
            trusted:
              packages: 'kz.bisen.springcourse.springpublishingwebapp.kafka'




  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/project2
    username: postgres
    password: postgres



  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: true



  mvc:
    hiddenmethod:
      filter:
        enabled: true



server:
  port: 8081