package kz.bisen.springwebapp1.project2Boot.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-12-09T16:40:24.901+06:00
 * Generated source version: 3.5.3
 *
 */
@WebServiceClient(name = "SoapBookService",
                  wsdlLocation = "file:/C:/Projects/project2Boot/src/main/resources/wsdl/wsdlFile.wsdl",
                  targetNamespace = "http://impl.soap.springpublishingwebapp.springcourse.bisen.kz/")
public class SoapBookService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.soap.springpublishingwebapp.springcourse.bisen.kz/", "SoapBookService");
    public final static QName SoapBookServicePort = new QName("http://impl.soap.springpublishingwebapp.springcourse.bisen.kz/", "SoapBookServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Projects/project2Boot/src/main/resources/wsdl/wsdlFile.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SoapBookService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Projects/project2Boot/src/main/resources/wsdl/wsdlFile.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SoapBookService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SoapBookService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapBookService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SoapBookService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SoapBookService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SoapBookService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SoapBookService
     */
    @WebEndpoint(name = "SoapBookServicePort")
    public SoapBookService getSoapBookServicePort() {
        return super.getPort(SoapBookServicePort, SoapBookService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapBookService
     */
    @WebEndpoint(name = "SoapBookServicePort")
    public SoapBookService getSoapBookServicePort(WebServiceFeature... features) {
        return super.getPort(SoapBookServicePort, SoapBookService.class, features);
    }

}
