CREATE TABLE reader (
                        reader_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        fullname varchar(100) NOT NULL UNIQUE,
                        birth_date int NOT NULL,
                        password varchar not null,
                        username varchar(20) not null,
                        role varchar(100) not null
);
CREATE TABLE book (
                      book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title varchar(50) NOT NULL,
                      author varchar(50) NOT NULL,
                      issue_year int NOT NULL,
                      reader_id int REFERENCES reader(reader_id) ON DELETE SET NULL,
                      datetime_taken timestamp
);

CREATE EXTENSION pg_trgm;

CREATE INDEX trgm_idx_book_title ON BOOK USING GIN(title gin_trgm_ops);