package kz.bisen.springcourse.springpublishingwebapp.soap.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-12-23T03:02:31.839+06:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://impl.soap.springpublishingwebapp.springcourse.bisen.kz/", name = "SoapBookService")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapBookService {

    @WebMethod(operationName = "get-books")
    @RequestWrapper(localName = "get-books", targetNamespace = "http://impl.soap.springpublishingwebapp.springcourse.bisen.kz/", className = "kz.bisen.springcourse.springpublishingwebapp.soap.impl.GetBooks")
    @ResponseWrapper(localName = "get-booksResponse", targetNamespace = "http://impl.soap.springpublishingwebapp.springcourse.bisen.kz/", className = "kz.bisen.springcourse.springpublishingwebapp.soap.impl.GetBooksResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<kz.bisen.springcourse.springpublishingwebapp.soap.impl.SoapBook> getBooks(

        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );
}
